/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Budgets service. Represents a row in the &quot;expensio_Budgets&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.expensio.common.data.model.impl.BudgetsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.expensio.common.data.model.impl.BudgetsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Budgets
 * @generated
 */
@ProviderType
public interface BudgetsModel
	extends BaseModel<Budgets>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a budgets model instance should use the {@link Budgets} interface instead.
	 */

	/**
	 * Returns the primary key of this budgets.
	 *
	 * @return the primary key of this budgets
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this budgets.
	 *
	 * @param primaryKey the primary key of this budgets
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this budgets.
	 *
	 * @return the uuid of this budgets
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this budgets.
	 *
	 * @param uuid the uuid of this budgets
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the budget ID of this budgets.
	 *
	 * @return the budget ID of this budgets
	 */
	public long getBudgetId();

	/**
	 * Sets the budget ID of this budgets.
	 *
	 * @param budgetId the budget ID of this budgets
	 */
	public void setBudgetId(long budgetId);

	/**
	 * Returns the company ID of this budgets.
	 *
	 * @return the company ID of this budgets
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this budgets.
	 *
	 * @param companyId the company ID of this budgets
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this budgets.
	 *
	 * @return the user ID of this budgets
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this budgets.
	 *
	 * @param userId the user ID of this budgets
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this budgets.
	 *
	 * @return the user uuid of this budgets
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this budgets.
	 *
	 * @param userUuid the user uuid of this budgets
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this budgets.
	 *
	 * @return the user name of this budgets
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this budgets.
	 *
	 * @param userName the user name of this budgets
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this budgets.
	 *
	 * @return the create date of this budgets
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this budgets.
	 *
	 * @param createDate the create date of this budgets
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this budgets.
	 *
	 * @return the modified date of this budgets
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this budgets.
	 *
	 * @param modifiedDate the modified date of this budgets
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the budget amount of this budgets.
	 *
	 * @return the budget amount of this budgets
	 */
	public Long getBudgetAmount();

	/**
	 * Sets the budget amount of this budgets.
	 *
	 * @param budgetAmount the budget amount of this budgets
	 */
	public void setBudgetAmount(Long budgetAmount);

	/**
	 * Returns the budget duration of this budgets.
	 *
	 * @return the budget duration of this budgets
	 */
	public Date getBudgetDuration();

	/**
	 * Sets the budget duration of this budgets.
	 *
	 * @param budgetDuration the budget duration of this budgets
	 */
	public void setBudgetDuration(Date budgetDuration);

	/**
	 * Returns the budget description of this budgets.
	 *
	 * @return the budget description of this budgets
	 */
	@AutoEscape
	public String getBudgetDescription();

	/**
	 * Sets the budget description of this budgets.
	 *
	 * @param budgetDescription the budget description of this budgets
	 */
	public void setBudgetDescription(String budgetDescription);

	/**
	 * Returns the budget department ID of this budgets.
	 *
	 * @return the budget department ID of this budgets
	 */
	public Long getBudgetDepartmentId();

	/**
	 * Sets the budget department ID of this budgets.
	 *
	 * @param budgetDepartmentId the budget department ID of this budgets
	 */
	public void setBudgetDepartmentId(Long budgetDepartmentId);

	@Override
	public Budgets cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}