/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employees service. Represents a row in the &quot;expensio_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.expensio.common.data.model.impl.EmployeesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.expensio.common.data.model.impl.EmployeesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employees
 * @generated
 */
@ProviderType
public interface EmployeesModel
	extends BaseModel<Employees>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employees model instance should use the {@link Employees} interface instead.
	 */

	/**
	 * Returns the primary key of this employees.
	 *
	 * @return the primary key of this employees
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employees.
	 *
	 * @param primaryKey the primary key of this employees
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employees.
	 *
	 * @return the uuid of this employees
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employees.
	 *
	 * @param uuid the uuid of this employees
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the employee ID of this employees.
	 *
	 * @return the employee ID of this employees
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employees.
	 *
	 * @param employeeId the employee ID of this employees
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this employees.
	 *
	 * @return the company ID of this employees
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employees.
	 *
	 * @param companyId the company ID of this employees
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employees.
	 *
	 * @return the user ID of this employees
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employees.
	 *
	 * @param userId the user ID of this employees
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employees.
	 *
	 * @return the user uuid of this employees
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employees.
	 *
	 * @param userUuid the user uuid of this employees
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employees.
	 *
	 * @return the user name of this employees
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employees.
	 *
	 * @param userName the user name of this employees
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employees.
	 *
	 * @return the create date of this employees
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employees.
	 *
	 * @param createDate the create date of this employees
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employees.
	 *
	 * @return the modified date of this employees
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employees.
	 *
	 * @param modifiedDate the modified date of this employees
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee user ID of this employees.
	 *
	 * @return the employee user ID of this employees
	 */
	public Long getEmployeeUserId();

	/**
	 * Sets the employee user ID of this employees.
	 *
	 * @param employeeUserId the employee user ID of this employees
	 */
	public void setEmployeeUserId(Long employeeUserId);

	/**
	 * Returns the department of this employees.
	 *
	 * @return the department of this employees
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this employees.
	 *
	 * @param department the department of this employees
	 */
	public void setDepartment(String department);

	/**
	 * Returns the designation of this employees.
	 *
	 * @return the designation of this employees
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this employees.
	 *
	 * @param designation the designation of this employees
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the status of this employees.
	 *
	 * @return the status of this employees
	 */
	public Boolean getStatus();

	/**
	 * Sets the status of this employees.
	 *
	 * @param status the status of this employees
	 */
	public void setStatus(Boolean status);

	@Override
	public Employees cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}