/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Expenses service. Represents a row in the &quot;expensio_Expenses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.expensio.common.data.model.impl.ExpensesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.expensio.common.data.model.impl.ExpensesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Expenses
 * @generated
 */
@ProviderType
public interface ExpensesModel
	extends BaseModel<Expenses>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expenses model instance should use the {@link Expenses} interface instead.
	 */

	/**
	 * Returns the primary key of this expenses.
	 *
	 * @return the primary key of this expenses
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expenses.
	 *
	 * @param primaryKey the primary key of this expenses
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this expenses.
	 *
	 * @return the uuid of this expenses
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this expenses.
	 *
	 * @param uuid the uuid of this expenses
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the expense ID of this expenses.
	 *
	 * @return the expense ID of this expenses
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this expenses.
	 *
	 * @param expenseId the expense ID of this expenses
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the company ID of this expenses.
	 *
	 * @return the company ID of this expenses
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this expenses.
	 *
	 * @param companyId the company ID of this expenses
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this expenses.
	 *
	 * @return the user ID of this expenses
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this expenses.
	 *
	 * @param userId the user ID of this expenses
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this expenses.
	 *
	 * @return the user uuid of this expenses
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this expenses.
	 *
	 * @param userUuid the user uuid of this expenses
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this expenses.
	 *
	 * @return the user name of this expenses
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this expenses.
	 *
	 * @param userName the user name of this expenses
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this expenses.
	 *
	 * @return the create date of this expenses
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this expenses.
	 *
	 * @param createDate the create date of this expenses
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this expenses.
	 *
	 * @return the modified date of this expenses
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this expenses.
	 *
	 * @param modifiedDate the modified date of this expenses
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the expense amount of this expenses.
	 *
	 * @return the expense amount of this expenses
	 */
	public Long getExpenseAmount();

	/**
	 * Sets the expense amount of this expenses.
	 *
	 * @param expenseAmount the expense amount of this expenses
	 */
	public void setExpenseAmount(Long expenseAmount);

	/**
	 * Returns the category ID of this expenses.
	 *
	 * @return the category ID of this expenses
	 */
	public Long getCategoryId();

	/**
	 * Sets the category ID of this expenses.
	 *
	 * @param categoryId the category ID of this expenses
	 */
	public void setCategoryId(Long categoryId);

	/**
	 * Returns the sub category ID of this expenses.
	 *
	 * @return the sub category ID of this expenses
	 */
	public Long getSubCategoryId();

	/**
	 * Sets the sub category ID of this expenses.
	 *
	 * @param subCategoryId the sub category ID of this expenses
	 */
	public void setSubCategoryId(Long subCategoryId);

	/**
	 * Returns the employee user ID of this expenses.
	 *
	 * @return the employee user ID of this expenses
	 */
	public Long getEmployeeUserId();

	/**
	 * Sets the employee user ID of this expenses.
	 *
	 * @param employeeUserId the employee user ID of this expenses
	 */
	public void setEmployeeUserId(Long employeeUserId);

	/**
	 * Returns the doc media of this expenses.
	 *
	 * @return the doc media of this expenses
	 */
	@AutoEscape
	public String getDocMedia();

	/**
	 * Sets the doc media of this expenses.
	 *
	 * @param docMedia the doc media of this expenses
	 */
	public void setDocMedia(String docMedia);

	@Override
	public Expenses cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}