/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Loginlogs service. Represents a row in the &quot;expensio_Loginlogs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.expensio.common.data.model.impl.LoginlogsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.expensio.common.data.model.impl.LoginlogsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Loginlogs
 * @generated
 */
@ProviderType
public interface LoginlogsModel extends BaseModel<Loginlogs> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loginlogs model instance should use the {@link Loginlogs} interface instead.
	 */

	/**
	 * Returns the primary key of this loginlogs.
	 *
	 * @return the primary key of this loginlogs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loginlogs.
	 *
	 * @param primaryKey the primary key of this loginlogs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this loginlogs.
	 *
	 * @return the uuid of this loginlogs
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this loginlogs.
	 *
	 * @param uuid the uuid of this loginlogs
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the login log ID of this loginlogs.
	 *
	 * @return the login log ID of this loginlogs
	 */
	public long getLoginLogId();

	/**
	 * Sets the login log ID of this loginlogs.
	 *
	 * @param loginLogId the login log ID of this loginlogs
	 */
	public void setLoginLogId(long loginLogId);

	/**
	 * Returns the user name of this loginlogs.
	 *
	 * @return the user name of this loginlogs
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this loginlogs.
	 *
	 * @param userName the user name of this loginlogs
	 */
	public void setUserName(String userName);

	/**
	 * Returns the email of this loginlogs.
	 *
	 * @return the email of this loginlogs
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this loginlogs.
	 *
	 * @param email the email of this loginlogs
	 */
	public void setEmail(String email);

	/**
	 * Returns the ip address of this loginlogs.
	 *
	 * @return the ip address of this loginlogs
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this loginlogs.
	 *
	 * @param ipAddress the ip address of this loginlogs
	 */
	public void setIpAddress(String ipAddress);

	/**
	 * Returns the uri of this loginlogs.
	 *
	 * @return the uri of this loginlogs
	 */
	@AutoEscape
	public String getUri();

	/**
	 * Sets the uri of this loginlogs.
	 *
	 * @param uri the uri of this loginlogs
	 */
	public void setUri(String uri);

	/**
	 * Returns the host of this loginlogs.
	 *
	 * @return the host of this loginlogs
	 */
	@AutoEscape
	public String getHost();

	/**
	 * Sets the host of this loginlogs.
	 *
	 * @param host the host of this loginlogs
	 */
	public void setHost(String host);

	/**
	 * Returns the login date time of this loginlogs.
	 *
	 * @return the login date time of this loginlogs
	 */
	public Date getLoginDateTime();

	/**
	 * Sets the login date time of this loginlogs.
	 *
	 * @param loginDateTime the login date time of this loginlogs
	 */
	public void setLoginDateTime(Date loginDateTime);

	@Override
	public Loginlogs cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}