/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model.impl;

import com.expensio.common.data.model.Designations;
import com.expensio.common.data.service.DesignationsLocalServiceUtil;

/**
 * The extended model base implementation for the Designations service. Represents a row in the &quot;expensio_Designations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DesignationsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DesignationsImpl
 * @see Designations
 * @generated
 */
public abstract class DesignationsBaseImpl
	extends DesignationsModelImpl implements Designations {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a designations model instance should use the <code>Designations</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DesignationsLocalServiceUtil.addDesignations(this);
		}
		else {
			DesignationsLocalServiceUtil.updateDesignations(this);
		}
	}

}