/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model.impl;

import com.expensio.common.data.model.Designations;
import com.expensio.common.data.model.DesignationsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Designations service. Represents a row in the &quot;expensio_Designations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DesignationsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DesignationsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DesignationsImpl
 * @generated
 */
@JSON(strict = true)
public class DesignationsModelImpl
	extends BaseModelImpl<Designations> implements DesignationsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a designations model instance should use the <code>Designations</code> interface instead.
	 */
	public static final String TABLE_NAME = "expensio_Designations";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"designationId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"designationName", Types.VARCHAR},
		{"departmentId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("designationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("designationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("departmentId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table expensio_Designations (uuid_ VARCHAR(75) null,designationId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,designationName VARCHAR(75) null,departmentId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table expensio_Designations";

	public static final String ORDER_BY_JPQL =
		" ORDER BY designations.designationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY expensio_Designations.designationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESIGNATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DesignationsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _designationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDesignationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _designationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Designations.class;
	}

	@Override
	public String getModelClassName() {
		return Designations.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Designations, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Designations, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Designations, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Designations)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Designations, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Designations, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Designations)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Designations, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Designations, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Designations, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Designations, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Designations, Object>>();

			attributeGetterFunctions.put("uuid", Designations::getUuid);
			attributeGetterFunctions.put(
				"designationId", Designations::getDesignationId);
			attributeGetterFunctions.put(
				"companyId", Designations::getCompanyId);
			attributeGetterFunctions.put("userId", Designations::getUserId);
			attributeGetterFunctions.put("userName", Designations::getUserName);
			attributeGetterFunctions.put(
				"createDate", Designations::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Designations::getModifiedDate);
			attributeGetterFunctions.put(
				"designationName", Designations::getDesignationName);
			attributeGetterFunctions.put(
				"departmentId", Designations::getDepartmentId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Designations, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Designations, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Designations, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<Designations, String>)Designations::setUuid);
			attributeSetterBiConsumers.put(
				"designationId",
				(BiConsumer<Designations, Long>)Designations::setDesignationId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Designations, Long>)Designations::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Designations, Long>)Designations::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Designations, String>)Designations::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Designations, Date>)Designations::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Designations, Date>)Designations::setModifiedDate);
			attributeSetterBiConsumers.put(
				"designationName",
				(BiConsumer<Designations, String>)
					Designations::setDesignationName);
			attributeSetterBiConsumers.put(
				"departmentId",
				(BiConsumer<Designations, Long>)Designations::setDepartmentId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getDesignationId() {
		return _designationId;
	}

	@Override
	public void setDesignationId(long designationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationId = designationId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDesignationName() {
		if (_designationName == null) {
			return "";
		}
		else {
			return _designationName;
		}
	}

	@Override
	public void setDesignationName(String designationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationName = designationName;
	}

	@JSON
	@Override
	public Long getDepartmentId() {
		return _departmentId;
	}

	@Override
	public void setDepartmentId(Long departmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_departmentId = departmentId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Designations.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Designations.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Designations toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Designations>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DesignationsImpl designationsImpl = new DesignationsImpl();

		designationsImpl.setUuid(getUuid());
		designationsImpl.setDesignationId(getDesignationId());
		designationsImpl.setCompanyId(getCompanyId());
		designationsImpl.setUserId(getUserId());
		designationsImpl.setUserName(getUserName());
		designationsImpl.setCreateDate(getCreateDate());
		designationsImpl.setModifiedDate(getModifiedDate());
		designationsImpl.setDesignationName(getDesignationName());
		designationsImpl.setDepartmentId(getDepartmentId());

		designationsImpl.resetOriginalValues();

		return designationsImpl;
	}

	@Override
	public Designations cloneWithOriginalValues() {
		DesignationsImpl designationsImpl = new DesignationsImpl();

		designationsImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		designationsImpl.setDesignationId(
			this.<Long>getColumnOriginalValue("designationId"));
		designationsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		designationsImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		designationsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		designationsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		designationsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		designationsImpl.setDesignationName(
			this.<String>getColumnOriginalValue("designationName"));
		designationsImpl.setDepartmentId(
			this.<Long>getColumnOriginalValue("departmentId"));

		return designationsImpl;
	}

	@Override
	public int compareTo(Designations designations) {
		int value = 0;

		if (getDesignationId() < designations.getDesignationId()) {
			value = -1;
		}
		else if (getDesignationId() > designations.getDesignationId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Designations)) {
			return false;
		}

		Designations designations = (Designations)object;

		long primaryKey = designations.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Designations> toCacheModel() {
		DesignationsCacheModel designationsCacheModel =
			new DesignationsCacheModel();

		designationsCacheModel.uuid = getUuid();

		String uuid = designationsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			designationsCacheModel.uuid = null;
		}

		designationsCacheModel.designationId = getDesignationId();

		designationsCacheModel.companyId = getCompanyId();

		designationsCacheModel.userId = getUserId();

		designationsCacheModel.userName = getUserName();

		String userName = designationsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			designationsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			designationsCacheModel.createDate = createDate.getTime();
		}
		else {
			designationsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			designationsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			designationsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		designationsCacheModel.designationName = getDesignationName();

		String designationName = designationsCacheModel.designationName;

		if ((designationName != null) && (designationName.length() == 0)) {
			designationsCacheModel.designationName = null;
		}

		Long departmentId = getDepartmentId();

		if (departmentId != null) {
			designationsCacheModel.departmentId = departmentId;
		}

		return designationsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Designations, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Designations, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Designations, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Designations)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Designations>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Designations.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _designationId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _designationName;
	private Long _departmentId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Designations, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Designations)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("designationId", _designationId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("designationName", _designationName);
		_columnOriginalValues.put("departmentId", _departmentId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("designationId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("designationName", 128L);

		columnBitmasks.put("departmentId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Designations _escapedModel;

}