/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model.impl;

import com.expensio.common.data.model.Employees;
import com.expensio.common.data.model.EmployeesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Employees service. Represents a row in the &quot;expensio_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeesImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeesModelImpl
	extends BaseModelImpl<Employees> implements EmployeesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employees model instance should use the <code>Employees</code> interface instead.
	 */
	public static final String TABLE_NAME = "expensio_Employees";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"employeeId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"employeeUserId", Types.BIGINT},
		{"department", Types.VARCHAR}, {"designation", Types.VARCHAR},
		{"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("department", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("designation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table expensio_Employees (uuid_ VARCHAR(75) null,employeeId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,employeeUserId LONG,department VARCHAR(75) null,designation VARCHAR(75) null,status BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table expensio_Employees";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employees.employeeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY expensio_Employees.employeeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Employees.class;
	}

	@Override
	public String getModelClassName() {
		return Employees.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Employees, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Employees, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Employees, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Employees)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Employees, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Employees, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Employees)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Employees, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Employees, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Employees, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Employees, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Employees, Object>>();

			attributeGetterFunctions.put("uuid", Employees::getUuid);
			attributeGetterFunctions.put(
				"employeeId", Employees::getEmployeeId);
			attributeGetterFunctions.put("companyId", Employees::getCompanyId);
			attributeGetterFunctions.put("userId", Employees::getUserId);
			attributeGetterFunctions.put("userName", Employees::getUserName);
			attributeGetterFunctions.put(
				"createDate", Employees::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Employees::getModifiedDate);
			attributeGetterFunctions.put(
				"employeeUserId", Employees::getEmployeeUserId);
			attributeGetterFunctions.put(
				"department", Employees::getDepartment);
			attributeGetterFunctions.put(
				"designation", Employees::getDesignation);
			attributeGetterFunctions.put("status", Employees::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Employees, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Employees, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Employees, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Employees, String>)Employees::setUuid);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<Employees, Long>)Employees::setEmployeeId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Employees, Long>)Employees::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Employees, Long>)Employees::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Employees, String>)Employees::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Employees, Date>)Employees::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Employees, Date>)Employees::setModifiedDate);
			attributeSetterBiConsumers.put(
				"employeeUserId",
				(BiConsumer<Employees, Long>)Employees::setEmployeeUserId);
			attributeSetterBiConsumers.put(
				"department",
				(BiConsumer<Employees, String>)Employees::setDepartment);
			attributeSetterBiConsumers.put(
				"designation",
				(BiConsumer<Employees, String>)Employees::setDesignation);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Employees, Boolean>)Employees::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Long getEmployeeUserId() {
		return _employeeUserId;
	}

	@Override
	public void setEmployeeUserId(Long employeeUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeUserId = employeeUserId;
	}

	@JSON
	@Override
	public String getDepartment() {
		if (_department == null) {
			return "";
		}
		else {
			return _department;
		}
	}

	@Override
	public void setDepartment(String department) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_department = department;
	}

	@JSON
	@Override
	public String getDesignation() {
		if (_designation == null) {
			return "";
		}
		else {
			return _designation;
		}
	}

	@Override
	public void setDesignation(String designation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designation = designation;
	}

	@JSON
	@Override
	public Boolean getStatus() {
		return _status;
	}

	@Override
	public void setStatus(Boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Employees.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Employees.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Employees toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Employees>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeesImpl employeesImpl = new EmployeesImpl();

		employeesImpl.setUuid(getUuid());
		employeesImpl.setEmployeeId(getEmployeeId());
		employeesImpl.setCompanyId(getCompanyId());
		employeesImpl.setUserId(getUserId());
		employeesImpl.setUserName(getUserName());
		employeesImpl.setCreateDate(getCreateDate());
		employeesImpl.setModifiedDate(getModifiedDate());
		employeesImpl.setEmployeeUserId(getEmployeeUserId());
		employeesImpl.setDepartment(getDepartment());
		employeesImpl.setDesignation(getDesignation());
		employeesImpl.setStatus(getStatus());

		employeesImpl.resetOriginalValues();

		return employeesImpl;
	}

	@Override
	public Employees cloneWithOriginalValues() {
		EmployeesImpl employeesImpl = new EmployeesImpl();

		employeesImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		employeesImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		employeesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeesImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		employeesImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		employeesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeesImpl.setEmployeeUserId(
			this.<Long>getColumnOriginalValue("employeeUserId"));
		employeesImpl.setDepartment(
			this.<String>getColumnOriginalValue("department"));
		employeesImpl.setDesignation(
			this.<String>getColumnOriginalValue("designation"));
		employeesImpl.setStatus(this.<Boolean>getColumnOriginalValue("status"));

		return employeesImpl;
	}

	@Override
	public int compareTo(Employees employees) {
		int value = 0;

		if (getEmployeeId() < employees.getEmployeeId()) {
			value = -1;
		}
		else if (getEmployeeId() > employees.getEmployeeId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Employees)) {
			return false;
		}

		Employees employees = (Employees)object;

		long primaryKey = employees.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Employees> toCacheModel() {
		EmployeesCacheModel employeesCacheModel = new EmployeesCacheModel();

		employeesCacheModel.uuid = getUuid();

		String uuid = employeesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeesCacheModel.uuid = null;
		}

		employeesCacheModel.employeeId = getEmployeeId();

		employeesCacheModel.companyId = getCompanyId();

		employeesCacheModel.userId = getUserId();

		employeesCacheModel.userName = getUserName();

		String userName = employeesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeesCacheModel.createDate = createDate.getTime();
		}
		else {
			employeesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Long employeeUserId = getEmployeeUserId();

		if (employeeUserId != null) {
			employeesCacheModel.employeeUserId = employeeUserId;
		}

		employeesCacheModel.department = getDepartment();

		String department = employeesCacheModel.department;

		if ((department != null) && (department.length() == 0)) {
			employeesCacheModel.department = null;
		}

		employeesCacheModel.designation = getDesignation();

		String designation = employeesCacheModel.designation;

		if ((designation != null) && (designation.length() == 0)) {
			employeesCacheModel.designation = null;
		}

		Boolean status = getStatus();

		if (status != null) {
			employeesCacheModel.status = status;
		}

		return employeesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Employees, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Employees, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Employees, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Employees)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Employees>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Employees.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _employeeId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Long _employeeUserId;
	private String _department;
	private String _designation;
	private Boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Employees, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Employees)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("employeeUserId", _employeeUserId);
		_columnOriginalValues.put("department", _department);
		_columnOriginalValues.put("designation", _designation);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("employeeId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("employeeUserId", 128L);

		columnBitmasks.put("department", 256L);

		columnBitmasks.put("designation", 512L);

		columnBitmasks.put("status", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Employees _escapedModel;

}