/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.common.data.model.impl;

import com.expensio.common.data.model.Loginlogs;
import com.expensio.common.data.model.LoginlogsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Loginlogs service. Represents a row in the &quot;expensio_Loginlogs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LoginlogsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoginlogsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoginlogsImpl
 * @generated
 */
@JSON(strict = true)
public class LoginlogsModelImpl
	extends BaseModelImpl<Loginlogs> implements LoginlogsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loginlogs model instance should use the <code>Loginlogs</code> interface instead.
	 */
	public static final String TABLE_NAME = "expensio_Loginlogs";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"loginLogId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"ipAddress", Types.VARCHAR}, {"uri", Types.VARCHAR},
		{"host", Types.VARCHAR}, {"loginDateTime", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loginLogId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uri", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("host", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loginDateTime", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table expensio_Loginlogs (uuid_ VARCHAR(75) null,loginLogId LONG not null primary key,userName VARCHAR(75) null,email VARCHAR(75) null,ipAddress VARCHAR(75) null,uri VARCHAR(75) null,host VARCHAR(75) null,loginDateTime DATE null)";

	public static final String TABLE_SQL_DROP = "drop table expensio_Loginlogs";

	public static final String ORDER_BY_JPQL =
		" ORDER BY loginlogs.loginLogId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY expensio_Loginlogs.loginLogId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOGINLOGID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LoginlogsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loginLogId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoginLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loginLogId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Loginlogs.class;
	}

	@Override
	public String getModelClassName() {
		return Loginlogs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Loginlogs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Loginlogs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Loginlogs, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Loginlogs)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Loginlogs, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Loginlogs, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Loginlogs)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Loginlogs, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Loginlogs, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Loginlogs, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Loginlogs, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Loginlogs, Object>>();

			attributeGetterFunctions.put("uuid", Loginlogs::getUuid);
			attributeGetterFunctions.put(
				"loginLogId", Loginlogs::getLoginLogId);
			attributeGetterFunctions.put("userName", Loginlogs::getUserName);
			attributeGetterFunctions.put("email", Loginlogs::getEmail);
			attributeGetterFunctions.put("ipAddress", Loginlogs::getIpAddress);
			attributeGetterFunctions.put("uri", Loginlogs::getUri);
			attributeGetterFunctions.put("host", Loginlogs::getHost);
			attributeGetterFunctions.put(
				"loginDateTime", Loginlogs::getLoginDateTime);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Loginlogs, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Loginlogs, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Loginlogs, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Loginlogs, String>)Loginlogs::setUuid);
			attributeSetterBiConsumers.put(
				"loginLogId",
				(BiConsumer<Loginlogs, Long>)Loginlogs::setLoginLogId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Loginlogs, String>)Loginlogs::setUserName);
			attributeSetterBiConsumers.put(
				"email", (BiConsumer<Loginlogs, String>)Loginlogs::setEmail);
			attributeSetterBiConsumers.put(
				"ipAddress",
				(BiConsumer<Loginlogs, String>)Loginlogs::setIpAddress);
			attributeSetterBiConsumers.put(
				"uri", (BiConsumer<Loginlogs, String>)Loginlogs::setUri);
			attributeSetterBiConsumers.put(
				"host", (BiConsumer<Loginlogs, String>)Loginlogs::setHost);
			attributeSetterBiConsumers.put(
				"loginDateTime",
				(BiConsumer<Loginlogs, Date>)Loginlogs::setLoginDateTime);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLoginLogId() {
		return _loginLogId;
	}

	@Override
	public void setLoginLogId(long loginLogId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loginLogId = loginLogId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@JSON
	@Override
	public String getUri() {
		if (_uri == null) {
			return "";
		}
		else {
			return _uri;
		}
	}

	@Override
	public void setUri(String uri) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uri = uri;
	}

	@JSON
	@Override
	public String getHost() {
		if (_host == null) {
			return "";
		}
		else {
			return _host;
		}
	}

	@Override
	public void setHost(String host) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_host = host;
	}

	@JSON
	@Override
	public Date getLoginDateTime() {
		return _loginDateTime;
	}

	@Override
	public void setLoginDateTime(Date loginDateTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loginDateTime = loginDateTime;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Loginlogs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Loginlogs toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Loginlogs>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoginlogsImpl loginlogsImpl = new LoginlogsImpl();

		loginlogsImpl.setUuid(getUuid());
		loginlogsImpl.setLoginLogId(getLoginLogId());
		loginlogsImpl.setUserName(getUserName());
		loginlogsImpl.setEmail(getEmail());
		loginlogsImpl.setIpAddress(getIpAddress());
		loginlogsImpl.setUri(getUri());
		loginlogsImpl.setHost(getHost());
		loginlogsImpl.setLoginDateTime(getLoginDateTime());

		loginlogsImpl.resetOriginalValues();

		return loginlogsImpl;
	}

	@Override
	public Loginlogs cloneWithOriginalValues() {
		LoginlogsImpl loginlogsImpl = new LoginlogsImpl();

		loginlogsImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		loginlogsImpl.setLoginLogId(
			this.<Long>getColumnOriginalValue("loginLogId"));
		loginlogsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		loginlogsImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		loginlogsImpl.setIpAddress(
			this.<String>getColumnOriginalValue("ipAddress"));
		loginlogsImpl.setUri(this.<String>getColumnOriginalValue("uri"));
		loginlogsImpl.setHost(this.<String>getColumnOriginalValue("host"));
		loginlogsImpl.setLoginDateTime(
			this.<Date>getColumnOriginalValue("loginDateTime"));

		return loginlogsImpl;
	}

	@Override
	public int compareTo(Loginlogs loginlogs) {
		int value = 0;

		if (getLoginLogId() < loginlogs.getLoginLogId()) {
			value = -1;
		}
		else if (getLoginLogId() > loginlogs.getLoginLogId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Loginlogs)) {
			return false;
		}

		Loginlogs loginlogs = (Loginlogs)object;

		long primaryKey = loginlogs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Loginlogs> toCacheModel() {
		LoginlogsCacheModel loginlogsCacheModel = new LoginlogsCacheModel();

		loginlogsCacheModel.uuid = getUuid();

		String uuid = loginlogsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			loginlogsCacheModel.uuid = null;
		}

		loginlogsCacheModel.loginLogId = getLoginLogId();

		loginlogsCacheModel.userName = getUserName();

		String userName = loginlogsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loginlogsCacheModel.userName = null;
		}

		loginlogsCacheModel.email = getEmail();

		String email = loginlogsCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			loginlogsCacheModel.email = null;
		}

		loginlogsCacheModel.ipAddress = getIpAddress();

		String ipAddress = loginlogsCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			loginlogsCacheModel.ipAddress = null;
		}

		loginlogsCacheModel.uri = getUri();

		String uri = loginlogsCacheModel.uri;

		if ((uri != null) && (uri.length() == 0)) {
			loginlogsCacheModel.uri = null;
		}

		loginlogsCacheModel.host = getHost();

		String host = loginlogsCacheModel.host;

		if ((host != null) && (host.length() == 0)) {
			loginlogsCacheModel.host = null;
		}

		Date loginDateTime = getLoginDateTime();

		if (loginDateTime != null) {
			loginlogsCacheModel.loginDateTime = loginDateTime.getTime();
		}
		else {
			loginlogsCacheModel.loginDateTime = Long.MIN_VALUE;
		}

		return loginlogsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Loginlogs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Loginlogs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Loginlogs, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Loginlogs)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Loginlogs>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Loginlogs.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _loginLogId;
	private String _userName;
	private String _email;
	private String _ipAddress;
	private String _uri;
	private String _host;
	private Date _loginDateTime;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Loginlogs, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Loginlogs)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("loginLogId", _loginLogId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("ipAddress", _ipAddress);
		_columnOriginalValues.put("uri", _uri);
		_columnOriginalValues.put("host", _host);
		_columnOriginalValues.put("loginDateTime", _loginDateTime);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("loginLogId", 2L);

		columnBitmasks.put("userName", 4L);

		columnBitmasks.put("email", 8L);

		columnBitmasks.put("ipAddress", 16L);

		columnBitmasks.put("uri", 32L);

		columnBitmasks.put("host", 64L);

		columnBitmasks.put("loginDateTime", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Loginlogs _escapedModel;

}