/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.expensio.data.model.impl;

import com.expensio.data.model.login_logs;
import com.expensio.data.service.login_logsLocalServiceUtil;

/**
 * The extended model base implementation for the login_logs service. Represents a row in the &quot;expensio_login_logs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link login_logsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see login_logsImpl
 * @see login_logs
 * @generated
 */
public abstract class login_logsBaseImpl
	extends login_logsModelImpl implements login_logs {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a login_logs model instance should use the <code>login_logs</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			login_logsLocalServiceUtil.addlogin_logs(this);
		}
		else {
			login_logsLocalServiceUtil.updatelogin_logs(this);
		}
	}

}